# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: cosmic
      POSTGRES_DB: cosmic_db
    ports:
      - 30000:5432